image: Visual Studio 2019 # образ для сборки

stack: node 12 # окружение

branches:
  only:
    -master

cache: node_modules # кеширование

install:
  - npm install

build: off

test_script:
  - npm run lint && npm test # скрипт тестирования